WITH
CENTRALIZADO AS (
	SELECT CODSOLICITUD
	FROM CATALOG_LHCL_PROD_BCP_EXPL.BCP_EDV_RBMBDN.T72496_CENTRALIZADO
	WHERE DESTIPESTADOSOLICITUD = 'ACEPTADAS' AND FECDESEMBOLSO IS NULL AND CODMES = 202510 AND TIPPRODUCTO = 'CC'
),
CREDITO_CONSUMO AS (
	SELECT CODSOLICITUD, MTOSOLICITADO, MTOAPROBADO, FECDESEMBOLSO, CODINTERNOCOMPUTACIONAL 
	FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.M_SOLICITUDCREDITOCONSUMO
),
CLIENTE AS (
	SELECT CODCLAVEPARTYCLI, CODINTERNOCOMPUTACIONAL
	FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.M_CLIENTE
),
DEUDORSBS AS (
	SELECT CODCLAVEPARTYCLI, FECDIA, DESTIPCREDITO, NBREMPSISTEMAFINANCIERO, DESTIPCLASIFRIESGO, DESTIPMONEDA, MTODEUDASOL
	FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.H_DEUDORSBSDETALLE
)
SELECT
	A.CODSOLICITUD,
	B.CODINTERNOCOMPUTACIONAL,
	B.MTOSOLICITADO,
	B.MTOAPROBADO,
	C.CODCLAVEPARTYCLI,
	D.DESTIPCREDITO,
	D.NBREMPSISTEMAFINANCIERO,
	D.DESTIPCLASIFRIESGO,
	D.DESTIPMONEDA,
	D.MTODEUDASOL
FROM CENTRALIZADO A
LEFT JOIN CREDITO_CONSUMO B ON(A.CODSOLICITUD = B.CODSOLICITUD)
LEFT JOIN CLIENTE C ON (B.CODINTERNOCOMPUTACIONAL = C.CODINTERNOCOMPUTACIONAL)
LEFT JOIN DEUDORSBS D ON (C.CODCLAVEPARTYCLI = D.CODCLAVEPARTYCLI);
