TP_COLABORADORANALISTA AS (
  SELECT
      FECDIA,
      CODMES,
      MATORGANICO,
      MATSUPERIOR,
      NBRAREAUNIDADORGANIZATIVA
  FROM (
      SELECT
          FECDIA,
          CODMES,
          CODMATRICULA    AS MATORGANICO,
          CODMATRICULASUP AS MATSUPERIOR,
          NBRAREAUNIDADORGANIZATIVA,
          ROW_NUMBER() OVER (
              PARTITION BY FECDIA, CODMATRICULA
              ORDER BY FECDIA DESC
          ) AS rn
      FROM TP_COLABORADOR
  ) x
  WHERE rn = 1
),
