ACUMULADOSOLICITUDES =
CALCULATE(
    SUM('WEEKLY'[CTDSOLICITUDES]),
    FILTER(
        ALL('WEEKLY'[NUMDIA]),
        'WEEKLY'[NUMDIA] <= MAX('WEEKLY'[NUMDIA])
            && 'WEEKLY'[CODMES] = MAX('WEEKLY'[CODMES])
    )
)
