-- BASE DE CLIENTES QUE QUIERO BUSCAR SI TIENEN UNA TRANSACCION DE ADELANTO DE SUELDO EN LOS ULTIMOS 6 MESES DE LA FECCREACION DE MI BASE
SELECT A.CODINTERNOCOMPUTACIONAL, B.CODCLAVEPARTYCLI, A.FECCREACION
FROM CATALOG_LHCL_PROD_BCP.BCP_EDV_RBMBDN.T72496_BASE_CENTRALIZADO A
LEFT JOIN CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.M_CLIENTE B
ON UPPER(TRIM(A.CODINTERNOCOMPUTACIONAL)) = UPPER(TRIM(B.CODINTERNOCOMPUTACIONAL))
WHERE A.CODINTERNOCOMPUTACIONAL IS NOT NULL AND A.TIPOPRODUCTO = 'CC' AND B.CODCLAVEPARTYCLI IS NOT NULL;

-- BASE DE TRANSACCIONES DE CUENTA SUELDO POR CLIENTES
SELECT FECTRX, TO_DATE(FECTRX) AS FECTRANSACCION, CODCLAVEPARTYCLI 
FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.H_TRANSACCIONADELANTOCUENTASUELDO;

-- LO QUE NECESITO ES DE MI FECCREACION DE MI BASE, VERIFICAR SI AL MENOS ESE CLIENTE TUVO 1 TRANSACCION DE ADELANTO DE CUENTA SUELDO EN LOS ULTIMOS 6 MESES DE LA FECCREACION
