WITH
TP_FECHA_TIPOCAMBIO AS (
    SELECT
        CAST(DATE_FORMAT(FECTIPCAMBIO, 'yyyMM') AS INT) AS CODMES,
        MAX(FECTIPCAMBIO) AS FECTIPCAMBIO
    FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.H_TIPOCAMBIO
    WHERE CAST(DATE_FORMAT(FECTIPCAMBIO, 'yyyMM') AS INT) BETWEEN 202001 AND 202012
      AND CODMONEDADESTINO = '0001'
      AND CODAPP = 'GLM'
    GROUP BY CAST(DATE_FORMAT(FECTIPCAMBIO, 'yyyMM') AS INT)
),

TP_DATA_TIPOCAMBIO AS (
    SELECT
        CAST(DATE_FORMAT(FECTIPCAMBIO, 'yyyMM') AS INT) AS CODMES,
        FECTIPCAMBIO,
        CODMONEDAORIGEN,
        CODMONEDADESTINO,
        MTOCAMBIOMONEDAORIGENMONEDADESTINO
    FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.H_TIPOCAMBIO
    WHERE CAST(DATE_FORMAT(FECTIPCAMBIO, 'yyyMM') AS INT) BETWEEN 202001 AND 202012
      AND CODMONEDADESTINO = '0001'
      AND CODAPP = 'GLM'
),

TIPO_CAMBIO AS (
    SELECT
        A.CODMES,
        A.FECTIPCAMBIO,
        A.CODMONEDAORIGEN,
        A.CODMONEDADESTINO,
        A.MTOCAMBIOMONEDAORIGENMONEDADESTINO
    FROM TP_DATA_TIPOCAMBIO A
    INNER JOIN TP_FECHA_TIPOCAMBIO B
        ON A.CODMES = B.CODMES
       AND A.FECTIPCAMBIO = B.FECTIPCAMBIO
)

SELECT *
FROM TIPO_CAMBIO;
