SELECT COUNT(DISTINCT a.OPORTUNIDAD) AS cantidad_cruzan
FROM CATALOG_LHCL_PROD_BCP.BCP_EDV_RBMBDN.T72496_BASE_CENTRALIZADO a
INNER JOIN catalog_lhcl_prod_bcp.bcp_udv_int_vu.m_solicitudtarjetacredito b
  ON a.OPORTUNIDAD = b.CODSOLICITUD;
