WITH
TP_SOLICITUDTARJETACREDITO AS (
  SELECT DISTINCT
    A.CODSOLICITUD,
    A.FECSOLICITUD,
    A.HORSOLICITUD,
    A.DESTIPFLUJOVENTATARJETACREDITO,
    UPPER(TRANSLATE(A.DESCAMPANIA, 'ÁÉÍÓÚÜÑáéíóúüñ', 'AEIOUUNAEIOUUN')) AS DESCAMPANIA,
    A.DESPRODUCTO,
    A.TIPESTADOSOLICITUD,
    A.DESTIPETAPA,
    A.DESMOTIVOCDA,
    A.DESCOMENTARIO,
    A.NBRMONEDA,
    A.MTOSOLICITADO,
    A.MTOAPROBADO,
    A.FECINICIOEVALUACION,
    A.HORINICIOEVALUACION,
    A.FECFINEVALUACION,
    A.HORFINEVALUACION,
    A.FECEMISIONTARJETACREDITO,
    A.CODMATRICULACOLABORADORAPROBADOR,
    A.CODMATRICULACOLABORADORVENDEDOR,
    A.CODINTERNOCOMPUTACIONAL,
    A.CODCOLABORADORVENDEDOR,
    A.MTOCUOTAMENSUALAPROBADO,
    A.PCTTASAEFECTIVAANUALSOLICITUD,
    A.MTOINGRESOBRUTOSOLICITUD
  FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.M_SOLICITUDTARJETACREDITO A
  WHERE A.CODTIPREGAPP IN ('0126O000001xsIYQAY','0126O000001h0WaQAI','0126O000001h0WbQAI')
    AND A.FECSOLICITUD >= DATE '2025-10-01'
),
M_SOLICITUDTARJETACREDITO AS (
	SELECT
		A.CODSOLICITUD,
		A.CODINTERNOCOMPUTACIONAL,
		A.FECSOLICITUD,
		DAY(A.FECSOLICITUD) AS DIASOLICITUD,
		MONTH(A.FECSOLICITUD) AS MESSOLICITUD,
		YEAR(A.FECSOLICITUD) AS ANIOSOLICITUD,
		date_format(A.FECSOLICITUD, 'yyyyMM') AS CODMES,
		A.HORSOLICITUD,
	    (CASE
	    	WHEN A.CODMATRICULACOLABORADORAPROBADOR IS NOT NULL THEN 'EVALUACION EN CENTRALIZADO'
	    	ELSE 'EVALUACION AUTOMATICA'
	    END) AS TIPOEVALUACION,
	    A.TIPESTADOSOLICITUD,
	    (CASE A.TIPESTADOSOLICITUD
	    	WHEN 'ACPD' THEN 'ACEPTADA'
	    	WHEN 'DCLD' THEN 'DENEGADA'
	    	WHEN 'ENPR' THEN 'EN PROCESO'
	    	WHEN 'IRFC' THEN 'INGRESADO'
	    	WHEN 'EEEL' THEN 'EN PROCESO DE CALIFICACION'
	    	WHEN 'DIGI' THEN 'DIGITADO'
	    	ELSE 'SIN DATA'
	    END) AS RESULTADOANALISTA,	    
	    (CASE
	    	WHEN A.TIPESTADOSOLICITUD = 'ACPD' AND A.DESTIPETAPA = 'CERRADA' THEN 'ACEPTADA'
	    	WHEN A.TIPESTADOSOLICITUD = 'DCLD' AND A.DESTIPETAPA = 'RECHAZADA' THEN 'DENEGADA'
	    	WHEN A.TIPESTADOSOLICITUD = 'ENPR' AND A.DESTIPETAPA = 'DESESTIMADA' THEN 'DESESTIMADA'
	    	WHEN A.TIPESTADOSOLICITUD = 'IRFC' AND A.DESTIPETAPA = 'PERDIDA' THEN 'DESESTIMADA'
	    	WHEN A.TIPESTADOSOLICITUD = 'ENPR' THEN 'EN PROCESO'
	    	WHEN A.TIPESTADOSOLICITUD = 'IRFC' THEN 'INGRESADO'
	    	WHEN A.TIPESTADOSOLICITUD = 'EEEL' THEN 'EN PROCESO DE CALIFICACION'
	    	WHEN A.TIPESTADOSOLICITUD = 'DIGI' THEN 'DIGITADO'
	    	ELSE 'SIN DATA'
	    END) AS ESTADO_F,
		A.DESPRODUCTO,
	    (CASE
	      WHEN A.DESTIPFLUJOVENTATARJETACREDITO IN ('EP','PTC','BT','AMPLIACION','UPGRADE','ADICIONAL') THEN 'TARJETA CREDITO STOCK'
	      WHEN A.DESTIPFLUJOVENTATARJETACREDITO IN ('SEGUNDA TC','TC') THEN 'TARJETA CREDITO NUEVA'
	      WHEN
	        INSTR(A.DESCAMPANIA, 'PRESTAMO TAR') > 0 OR
	        INSTR(A.DESCAMPANIA, 'PTC') > 0 OR
	        INSTR(A.DESCAMPANIA, 'EP') > 0 OR
	        INSTR(A.DESCAMPANIA, 'BALANCE TRA') > 0 OR
	        INSTR(A.DESCAMPANIA, 'TC+BT') > 0 OR
	        INSTR(A.DESCAMPANIA, 'BT') > 0 OR
	        INSTR(A.DESCAMPANIA, 'AMPLIACION') > 0 OR
	        INSTR(A.DESCAMPANIA, 'UPGRADE') > 0 OR
	        INSTR(A.DESCAMPANIA, 'UPG') > 0 OR
	        INSTR(A.DESCAMPANIA, 'ADICIONAL') > 0
	        THEN 'TARJETA CREDITO STOCK'
	      ELSE 'SIN DATA'
	    END) AS TIPOPRODUCTO,
	    (CASE
	      WHEN A.DESTIPFLUJOVENTATARJETACREDITO = 'EP' THEN 'PTC'
	      WHEN A.DESTIPFLUJOVENTATARJETACREDITO = 'SEGUNDA TC' THEN 'TC'
	      WHEN A.DESTIPFLUJOVENTATARJETACREDITO IS NOT NULL THEN A.DESTIPFLUJOVENTATARJETACREDITO
	      WHEN INSTR(A.DESCAMPANIA, 'PRESTAMO TAR') > 0 OR INSTR(A.DESCAMPANIA, 'PTC') > 0 OR INSTR(A.DESCAMPANIA, 'EP') > 0 THEN 'PTC'
	      WHEN INSTR(A.DESCAMPANIA, 'BALANCE TRA') > 0 OR INSTR(A.DESCAMPANIA, 'TC+BT') > 0 OR INSTR(A.DESCAMPANIA, 'BT') > 0 THEN 'BT'
	      WHEN INSTR(A.DESCAMPANIA, 'AMPLIACION') > 0 THEN 'AMPLIACION'
	      WHEN INSTR(A.DESCAMPANIA, 'UPGRADE') > 0 OR INSTR(A.DESCAMPANIA, 'UPG') > 0 THEN 'UPGRADE'
	      WHEN INSTR(A.DESCAMPANIA, 'ADICIONAL') > 0 THEN 'ADICIONAL'
	      ELSE 'SIN DATA'
	    END) AS SUBPRODUCTO,
		A.DESTIPETAPA,
		A.DESMOTIVOCDA,
		A.DESCOMENTARIO,
		A.DESCAMPANIA,
	    (CASE
	      WHEN INSTR(A.DESCAMPANIA, '100%') > 0 THEN '100% APROBADO'
	      WHEN INSTR(A.DESCAMPANIA, 'PREAPR') > 0 THEN 'PREAPROBADO'
	      WHEN INSTR(A.DESCAMPANIA, 'SIN CAMP') > 0 THEN 'SIN CAMPANIA'
	      WHEN INSTR(A.DESCAMPANIA, 'INVITA') > 0 THEN 'INVITADO'
	      WHEN A.DESTIPFLUJOVENTATARJETACREDITO = 'EP' THEN 'PTC'
	      WHEN A.DESTIPFLUJOVENTATARJETACREDITO = 'SEGUNDA TC' THEN 'TC'
	      WHEN A.DESTIPFLUJOVENTATARJETACREDITO IS NOT NULL THEN A.DESTIPFLUJOVENTATARJETACREDITO
	      WHEN INSTR(A.DESCAMPANIA, 'PRESTAMO TAR') > 0 OR INSTR(A.DESCAMPANIA, 'PTC') > 0 OR INSTR(A.DESCAMPANIA, 'EP') > 0 THEN 'PTC'
	      WHEN INSTR(A.DESCAMPANIA, 'BALANCE TRA') > 0 OR INSTR(A.DESCAMPANIA, 'TC+BT') > 0 OR INSTR(A.DESCAMPANIA, 'BT') > 0 THEN 'BT'
	      WHEN INSTR(A.DESCAMPANIA, 'AMPLIACION') > 0 THEN 'AMPLIACION'
	      WHEN INSTR(A.DESCAMPANIA, 'UPGRADE') > 0 OR INSTR(A.DESCAMPANIA, 'UPG') > 0 THEN 'UPGRADE'
	      WHEN INSTR(A.DESCAMPANIA, 'ADICIONAL') > 0 THEN 'ADICIONAL'
	      ELSE 'SIN DATA'
	    END) AS DESCAMPANIACORTA,
	    A.NBRMONEDA,
	    (CASE 
	    	WHEN A.NBRMONEDA LIKE '%DOLAR%' THEN A.MTOSOLICITADO * 3.81
	    	ELSE A.MTOSOLICITADO
	    END) AS MTOSOLICITADOSOLES,
	    (CASE 
	    	WHEN A.NBRMONEDA LIKE '%DOLAR%' THEN A.MTOAPROBADO * 3.81
	    	ELSE A.MTOAPROBADO
	    END) AS MTOAPROBADOSOLES,
	    A.MTOSOLICITADO,
	    A.MTOAPROBADO,
	    TO_TIMESTAMP(CONCAT_WS(' ', A.FECINICIOEVALUACION, LPAD(A.HORINICIOEVALUACION, 6, '0')), 'yyyy-MM-dd HHmmss') AS INICIOEVALUACION,
	    TO_TIMESTAMP(CONCAT_WS(' ', A.FECFINEVALUACION, LPAD(A.HORFINEVALUACION, 6, '0')), 'yyyy-MM-dd HHmmss') AS FINEVALUACION,
	    A.FECEMISIONTARJETACREDITO,
	    A.CODMATRICULACOLABORADORAPROBADOR AS MATANALISTA,
	    A.CODMATRICULACOLABORADORVENDEDOR AS MTVENDEDOR,
	    A.CODCOLABORADORVENDEDOR,
	    A.MTOCUOTAMENSUALAPROBADO AS CUOTAMENSUALAPROBADO,
	    A.PCTTASAEFECTIVAANUALSOLICITUD AS TASASOLICITADA,
	    A.MTOINGRESOBRUTOSOLICITUD,
	    TO_TIMESTAMP(CONCAT_WS(' ', A.FECSOLICITUD, LPAD(A.HORSOLICITUD, 6, '0')), 'yyyy-MM-dd HHmmss') AS FECREGISTRO
    FROM TP_SOLICITUDTARJETACREDITO A
),
M_SOLICITUDINDIVIDUO_TITULAR AS (
	SELECT
		CODSOLICITUD,
		FLGCLIPAGOHABERESBCP AS CLIENTEBCPPDHTITULAR,
		TIPRENTA AS TIPRENTATITULAR,
		NUMPUNTAJEPRECALIF AS SCOREEVALUACIONTITULAR,
		TIPPARTYIDENTIFICACION AS TIPIDCTITULAR,
		MTOINGRESODIGITADO AS MTOINGRESOBRUTOTITULAR,
		MTOOTROINGRESODIGITADO AS MTOOTROINGRESOBRUTOTITULAR,
		MTOINGRESOCALCULADO AS MTOINGRESOPROMEDIOTITULAR,
		DESSUBSEGMENTO AS SEGMENTOTITULAR,
		CODSEGMENTORIESGOSCORE AS SEGMENTORIESGOTITULAR,
		DESTIPNIVELEDUCACIONAL AS GRADOINSTRUCCIONTITULAR,
		DESTIPOCUPACION AS SITUACIONLABORALTITULAR,
		NUMDEPENDIENTE AS NUMDEPENDIENTESTITULAR,
		DESTIPESTCIVIL AS ESTADOCIVILTITULAR,
	    MTOCEM AS MTOCEMTITULAR,
	    MTOCEMASESORVENTA AS MTOCEMASESORVENTATITULAR,
	    MTOCEMANALISTACREDITO AS MTOCEMANALISTACREDITOTITULAR,
	    (CASE
	    	WHEN NUMPUNTAJEPRECALIF <= 0 THEN 'SIN DATA'
	    	WHEN NUMPUNTAJEPRECALIF > 0 AND NUMPUNTAJEPRECALIF <= 300 THEN 'A. 1 - 300'
	    	WHEN NUMPUNTAJEPRECALIF > 300 AND NUMPUNTAJEPRECALIF <= 330 THEN 'B. >300 - 330'
	    	WHEN NUMPUNTAJEPRECALIF > 330 AND NUMPUNTAJEPRECALIF <= 360 THEN 'C. >330 - 360'
	    	WHEN NUMPUNTAJEPRECALIF > 360 AND NUMPUNTAJEPRECALIF <= 390 THEN 'D. >360 - 390'
	    	WHEN NUMPUNTAJEPRECALIF > 390 AND NUMPUNTAJEPRECALIF <= 420 THEN 'E. >390 - 420'
	    	WHEN NUMPUNTAJEPRECALIF > 420 AND NUMPUNTAJEPRECALIF <= 450 THEN 'F. >420 - 450'
	    	ELSE 'G. >450'
	    END) AS RANGOSCORETITULAR
	FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.M_SOLICITUDINDIVIDUO
	WHERE DESTIPROLSOLICITUD = 'TITULAR'
),
M_SOLICITUDINDIVIDUO_CONYUGE AS (
  SELECT
    CODSOLICITUD,
    TIPRENTA AS TIPRENTACONYUGE,
    TIPPARTYIDENTIFICACION AS TIPIDCCONYUGE,
    MTOINGRESODIGITADO AS MTOINGRESOBRUTOCONYUGE,
    MTOOTROINGRESODIGITADO AS MTOOTROINGRESOBRUTOCONYUGE,
    MTOINGRESOCALCULADO AS MTOINGRESOPROMEDIOCONYUGE,
    MTOCEM AS MTOCEMCONYUGE,
    MTOCEMASESORVENTA AS MTOCEMASESORVENTACONYUGE,
    MTOCEMANALISTACREDITO AS MTOCEMANALISTACREDITOCONYUGE,
    CODSEGMENTORIESGOSCORE AS SEGMENTORIESGOCONYUGE,
    DESTIPOCUPACION AS SITUACIONLABORALCONYUGE
  FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.M_SOLICITUDINDIVIDUO
  WHERE DESTIPROLSOLICITUD = 'CONYUGE'
),
M_SOLICITUDPARTY_TITULAR AS (
	SELECT
		CODSOLICITUD,
		DESTIPCLASIFRIESGOCLI AS CLASIFICACIONSBSTITULAR
	FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.M_SOLICITUDPARTY
	WHERE DESTIPROLSOLICITUD = 'TITULAR'
),
M_SOLICITUDPARTY_CONYUGE AS (
  SELECT
    CODSOLICITUD,
    DESTIPCLASIFRIESGOCLI AS CLASIFICACIONSBSCONYUGE
  FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.M_SOLICITUDPARTY
  WHERE DESTIPROLSOLICITUD = 'CONYUGE'
),
USERAPP AS (
  SELECT
    CODUSUARIOAPP,
    DESPOSICIONCOLABORADOR
  FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.M_USUARIOAPLICATIVO
),
TP_BASE AS (
	SELECT
		A.CODSOLICITUD,
		A.CODINTERNOCOMPUTACIONAL,
		A.FECSOLICITUD,
		A.DIASOLICITUD,
		A.MESSOLICITUD,
		A.ANIOSOLICITUD,
		A.CODMES,
		A.HORSOLICITUD,
		A.TIPOEVALUACION,
		A.TIPESTADOSOLICITUD,
		A.RESULTADOANALISTA,
		A.ESTADO_F,
		A.DESPRODUCTO,
		A.TIPOPRODUCTO,
		A.SUBPRODUCTO,
		A.DESTIPETAPA,
		A.DESMOTIVOCDA,
		A.DESCOMENTARIO,
		A.DESCAMPANIA,
		A.DESCAMPANIACORTA,
		A.NBRMONEDA,
		A.MTOSOLICITADOSOLES,
		(CASE
			WHEN A.MTOSOLICITADOSOLES <= 0 THEN 'SIN DATA'
			WHEN A.MTOSOLICITADOSOLES > 0 AND A.MTOSOLICITADOSOLES <= 23000 THEN 'A. 0 - 23k'
			WHEN A.MTOSOLICITADOSOLES > 23000 AND A.MTOSOLICITADOSOLES <= 46000 THEN 'B. >23k - 46k'
			WHEN A.MTOSOLICITADOSOLES > 46000 AND A.MTOSOLICITADOSOLES <= 69000 THEN 'C. >46k - 69k'
			WHEN A.MTOSOLICITADOSOLES > 69000 AND A.MTOSOLICITADOSOLES <= 92000 THEN 'D. >69k - 92k'
			WHEN A.MTOSOLICITADOSOLES > 92000 AND A.MTOSOLICITADOSOLES <= 115000 THEN 'E. >92k - 115k'
			WHEN A.MTOSOLICITADOSOLES > 115000 AND A.MTOSOLICITADOSOLES <= 138000 THEN 'F. >115k - 138k'
			WHEN A.MTOSOLICITADOSOLES > 138000 AND A.MTOSOLICITADOSOLES <= 160000 THEN 'G. >138k - 160k'
			ELSE 'H. >160k'
		END) AS RANGOMTOSOLICITADOSOLES,
		A.MTOAPROBADOSOLES,
		A.MTOSOLICITADO,
		A.MTOAPROBADO,
		TO_TIMESTAMP(CONCAT_WS(' ', A.FECSOLICITUD, LPAD(A.HORSOLICITUD, 6, '0')), 'yyyy-MM-dd HHmmss') AS FECREGISTRO,
		A.INICIOEVALUACION,
		A.FINEVALUACION,
		A.FECEMISIONTARJETACREDITO,
		A.MATANALISTA,
		A.MTVENDEDOR,
		A.CUOTAMENSUALAPROBADO,
		A.TASASOLICITADA,
		A.MTOINGRESOBRUTOSOLICITUD,
		A.FECREGISTRO,
		date_diff(SECOND, A.FECREGISTRO, A.FINEVALUACION)/3600 AS TIEMPOCLIENTEHRS,
		date_diff(SECOND, A.INICIOEVALUACION, A.FINEVALUACION)/3600 AS TIEMPOANALISTAHRS,
		date_diff(SECOND, A.FECREGISTRO, A.FINEVALUACION) AS TIEMPOCLIENTESEGUNDOS,
		date_diff(SECOND, A.INICIOEVALUACION, A.FINEVALUACION) AS TIEMPOANALISTASEGUNDOS,
		B.CLIENTEBCPPDHTITULAR,
		B.TIPRENTATITULAR,
		C.TIPRENTACONYUGE,
		B.SCOREEVALUACIONTITULAR,
		B.TIPIDCTITULAR,
		C.TIPIDCCONYUGE,
		B.MTOINGRESOBRUTOTITULAR,
		C.MTOINGRESOBRUTOCONYUGE,
		B.MTOOTROINGRESOBRUTOTITULAR,
		C.MTOOTROINGRESOBRUTOCONYUGE,
		B.MTOINGRESOPROMEDIOTITULAR,
		C.MTOINGRESOPROMEDIOCONYUGE,
		B.MTOCEMTITULAR,
		C.MTOCEMCONYUGE,
		B.MTOCEMASESORVENTATITULAR,
		C.MTOCEMASESORVENTACONYUGE,
		B.MTOCEMANALISTACREDITOTITULAR,
		C.MTOCEMANALISTACREDITOCONYUGE,
		B.SEGMENTOTITULAR,
		B.SEGMENTORIESGOTITULAR,
		C.SEGMENTORIESGOCONYUGE,
		B.GRADOINSTRUCCIONTITULAR,
		B.SITUACIONLABORALTITULAR,
		C.SITUACIONLABORALCONYUGE,
		B.NUMDEPENDIENTESTITULAR,
		B.ESTADOCIVILTITULAR,
		B.RANGOSCORETITULAR,
		D.CLASIFICACIONSBSTITULAR,
		E.CLASIFICACIONSBSCONYUGE,
		F.DESPOSICIONCOLABORADOR
	FROM M_SOLICITUDTARJETACREDITO A
	LEFT JOIN M_SOLICITUDINDIVIDUO_TITULAR B ON (A.CODSOLICITUD = B.CODSOLICITUD)
	LEFT JOIN M_SOLICITUDINDIVIDUO_CONYUGE C ON (A.CODSOLICITUD = C.CODSOLICITUD)
	LEFT JOIN M_SOLICITUDPARTY_TITULAR D ON (A.CODSOLICITUD = D.CODSOLICITUD)
	LEFT JOIN M_SOLICITUDPARTY_CONYUGE E ON (A.CODSOLICITUD = E.CODSOLICITUD)
	LEFT JOIN USERAPP F ON (A.CODCOLABORADORVENDEDOR = F.CODUSUARIOAPP)
)
SELECT
	A.*,
	(CASE
		WHEN TIEMPOCLIENTEHRS IS NULL THEN NULL
		WHEN TIEMPOCLIENTEHRS >= 0 and TIEMPOCLIENTEHRS <= 24 THEN 'DENTRO 24HRS'
		WHEN TIEMPOCLIENTEHRS > 24 THEN 'MAYOR 24HRS'
		ELSE 'SIN DATA'
	END) AS ATENCION24HRSCLIENTE,
	(CASE
		WHEN TIEMPOCLIENTEHRS IS NULL THEN NULL
		WHEN TIEMPOCLIENTEHRS >= 0 AND TIEMPOCLIENTEHRS <= 12 THEN 'DENTRO 12HRS'
		WHEN TIEMPOCLIENTEHRS > 12 AND TIEMPOCLIENTEHRS <= 24 THEN 'DENTRO 24HRS'
		WHEN TIEMPOCLIENTEHRS > 24 THEN 'MAYOR 24HRS'
		ELSE 'SIN DATA'
	END) AS ATENCION12HRSCLIENTE,
	(CASE
		WHEN TIEMPOCLIENTEHRS IS NULL THEN NULL
		WHEN TIEMPOCLIENTEHRS > 0 AND TIEMPOCLIENTEHRS <= 3 THEN 'A. 0 - 3'
		WHEN TIEMPOCLIENTEHRS > 3 AND TIEMPOCLIENTEHRS <= 6 THEN 'B. >3 - 6'
		WHEN TIEMPOCLIENTEHRS > 6 AND TIEMPOCLIENTEHRS <= 12 THEN 'C. >6 - 12'
		WHEN TIEMPOCLIENTEHRS > 12 AND TIEMPOCLIENTEHRS <= 18 THEN 'D. >12 - 18'
		WHEN TIEMPOCLIENTEHRS > 18 AND TIEMPOCLIENTEHRS <= 24 THEN 'E. >18 - 24'
		WHEN TIEMPOCLIENTEHRS > 24 THEN 'F. >24'
		ELSE 'SIN DATA'
	END) AS RANGOATENCIONCLIENTE
FROM TP_BASE A;