		
		-- UNIDADES: APROBADO / DENEGADO
		(CASE WHEN ESTADOSOLICITUD = 'RECHAZADO' THEN 1 ELSE 0 END) AS FLGDENEGADA,
		(CASE WHEN ESTADOSOLICITUD = 'RECHAZADO' THEN 1 ELSE 0 END) AS FLGDENEGADAINTEGRA,
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND MTOAPROBADO < MTOSOLICITADO AND MTOAPROBADO > 0 THEN 1 ELSE 0 END) AS FLGDENEGADAPARCIAL,
		
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' THEN 1 ELSE 0 END) AS FLGAPROBADA,
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND MTOAPROBADO = MTOSOLICITADO THEN 1 ELSE 0 END) AS FLGAPROBADAINTEGRA,
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND MTOAPROBADO < MTOSOLICITADO AND MTOAPROBADO > 0 THEN 1 ELSE 0 END) AS FLGAPROBADAPARCIAL,
		
		-- UNIDADES: DESEMBOLSO / NO DESEMBOLSO
		
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND FECDESEMBOLSO IS NOT NULL AND MTODESEMBOLSADO > 0 THEN 1 ELSE 0 END) AS FLGDESEMBOLSADA,
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND FECDESEMBOLSO IS NOT NULL AND MTODESEMBOLSADO = MTOAPROBADO THEN 1 ELSE 0 END) AS FLGDESEMBOLSADAINTEGRA,
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND FECDESEMBOLSO IS NOT NULL AND MTODESEMBOLSADO < MTOAPROBADO AND MTODESEMBOLSADO > 0 THEN 1 ELSE 0 END) AS FLGDESEMBOLSADOPARCIAL,
		
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND (FECDESEMBOLSO IS NULL OR MTODESEMBOLSADO = 0) THEN 1 ELSE 0 END) AS FLGNODESEMBOLSADAINGREGA,
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND FECDESEMBOLSO IS NOT NULL AND MTODESEMBOLSADO < MTOAPROBADO AND MTODESEMBOLSADO > 0 THEN 1 ELSE 0 END) AS FLGNODESEMBOLSADOPARCIAL,
		
		 -- MONTOS: APROBADO / DENEGADO
		 
		(CASE WHEN ESTADOSOLICITUD = 'RECHAZADO' THEN MTOSOLICITADO ELSE 0 END) AS MTODENEGADOINTEGRO,
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND MTOAPROBADO < MTOSOLICITADO AND MTOAPROBADO > 0 THEN MTOSOLICITADO - MTOAPROBADO ELSE 0 END) AS MTODENEGADOPARCIAL,
		((CASE WHEN ESTADOSOLICITUD = 'RECHAZADO' THEN MTOSOLICITADO ELSE 0 END) + (CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND MTOAPROBADO < MTOSOLICITADO AND MTOAPROBADO > 0 THEN MTOSOLICITADO - MTOAPROBADO ELSE 0 END) ) AS MTODENEGADO,
		
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' THEN MTOAPROBADO ELSE 0 END) AS MTOAPROBADO,
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND MTOAPROBADO = MTOSOLICITADO THEN MTOAPROBADO ELSE 0 END) AS MTOAPROBADOINTEGRO,
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND MTOAPROBADO < MTOSOLICITADO AND MTOAPROBADO > 0 THEN MTOAPROBADO ELSE 0 END) AS MTOAPROBADOPARCIAL,
		
		-- MONTOS: DESEMBOLSADO / NO DESEMBOLSADO
		
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND FECDESEMBOLSO IS NOT NULL AND MTODESEMBOLSADO > 0 THEN MTODESEMBOLSADO ELSE 0 END) AS MTODESEMBOLSADO,
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND FECDESEMBOLSO IS NOT NULL AND MTODESEMBOLSADO = MTOAPROBADO THEN MTODESEMBOLSADO ELSE 0 END) AS MTODESEMBOLSADOINTEGRO,
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND FECDESEMBOLSO IS NOT NULL AND MTODESEMBOLSADO < MTOAPROBADO AND MTODESEMBOLSADO > 0 THEN MTODESEMBOLSADO ELSE 0 END) AS MTODESEMBOLSADOPARCIAL,
		
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND (FECDESEMBOLSO IS NULL OR MTODESEMBOLSADO = 0) THEN MTOAPROBADO ELSE 0 END) AS MTONODESEMBOLSADOINTEGRO,
		(CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND FECDESEMBOLSO IS NOT NULL AND MTODESEMBOLSADO < MTOAPROBADO AND MTODESEMBOLSADO > 0 THEN MTOAPROBADO - MTODESEMBOLSADO ELSE 0 END) AS MTONODESEMBOLSADOPARCIAL,
		( (CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND (FECDESEMBOLSO IS NULL OR MTODESEMBOLSADO = 0) THEN MTOAPROBADO ELSE 0 END) + (CASE WHEN ESTADOSOLICITUD = 'APROBADO' AND FECDESEMBOLSO IS NOT NULL AND MTODESEMBOLSADO < MTOAPROBADO AND MTODESEMBOLSADO > 0 THEN MTOAPROBADO - MTODESEMBOLSADO ELSE 0 END) ) AS MTONODESEMBOLSADO
