WITH SOL AS (
  SELECT
    A.CODMESEVALUACION,
    A.FECSOLICITUDEVALUACION,
    A.FECEVALUACION,
    A.DESCANALVENTARBMPER,
    A.TIPPRODUCTOSOLICITUDRBM,
    A.DESCANALVENTASOLICITUDRBM,
    A.DESTIPDECISIONRESULTADORBM,
    TRIM(regexp_replace(A.CODINTERNOCOMPUTACIONAL, '[\\n\\r\\t]', '')) AS CODINTERNOCOMPUTACIONAL,
    A.DESTIPDECISIONRESULTADOPRIORIZACION,
    A.DESCAMPANIASOLICITUD,
    A.DESTIPEVALUACIONSOLICITUDCREDITO,
    A.CODIDEVALUACION,
    A.CODEVALUACIONSOLICITUD,
    A.CODSECUENCIALDECISIONRBM,
    A.NUMSOLICITUDEVALUACION,
    (CASE
      WHEN A.DESCANALVENTARBMPER = 'SALEFORCE' THEN SUBSTR(TRIM(A.NUMSOLICITUDEVALUACION), 5, 7)
      WHEN A.DESCANALVENTARBMPER = 'LOANS'     THEN SUBSTR(TRIM(A.NUMSOLICITUDEVALUACION), 3, 8)
      ELSE TRIM(A.NUMSOLICITUDEVALUACION)
    END) AS NUMSOLICITUDEVALUACIONCORTO,
    B.CODCLAVEPARTYCLI
  FROM CATALOG_LHCL_PROD_BCP.BCP_DDV_RBMRBMPER_MODELOGESTION_VU.MD_EVALUACIONSOLICITUDCREDITO A
  LEFT JOIN CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.M_CLIENTE B
    ON TRIM(regexp_replace(A.CODINTERNOCOMPUTACIONAL, '[\\n\\r\\t]', '')) = TRIM(B.CODINTERNOCOMPUTACIONAL)
  WHERE 
  	A.TIPPRODUCTOSOLICITUDRBM = 'CC'
    AND A.DESCANALVENTARBMPER NOT IN ('YAPE', 'OTROS')
    AND A.DESTIPDECISIONRESULTADORBM IN ('Approve', 'Decline', 'Investigate')
    AND A.CODINTERNOCOMPUTACIONAL IS NOT NULL
    AND TRIM(regexp_replace(A.CODINTERNOCOMPUTACIONAL, '[\\n\\r\\t]', '')) <> ''
),

SOL_NORM AS (
  SELECT
    s.*,
    CASE WHEN s.CODEVALUACIONSOLICITUD LIKE 'OP-%' THEN 1 ELSE 0 END AS FLG_OP_PREFIX,
    COALESCE(
      CAST(NULLIF(regexp_extract(s.CODEVALUACIONSOLICITUD, '([0-9]+)', 1), '') AS BIGINT),
      -1
    ) AS CODEVAL_NUM
  FROM SOL s
),

SOL_ORD AS (
  SELECT
    n.*,
    ROW_NUMBER() OVER (
      PARTITION BY n.CODINTERNOCOMPUTACIONAL
      ORDER BY
        n.FECSOLICITUDEVALUACION ASC,
        n.FLG_OP_PREFIX ASC,
        n.CODEVAL_NUM ASC,
        n.CODEVALUACIONSOLICITUD ASC,
        n.CODSECUENCIALDECISIONRBM ASC,
        n.CODIDEVALUACION ASC
    ) AS RN_SOL,

    LAG(n.FECSOLICITUDEVALUACION) OVER (
      PARTITION BY n.CODINTERNOCOMPUTACIONAL
      ORDER BY
        n.FECSOLICITUDEVALUACION ASC,
        n.FLG_OP_PREFIX ASC,
        n.CODEVAL_NUM ASC,
        n.CODEVALUACIONSOLICITUD ASC,
        n.CODSECUENCIALDECISIONRBM ASC,
        n.CODIDEVALUACION ASC
    ) AS PREV_FECSOL,

    LAG(n.FLG_OP_PREFIX) OVER (
      PARTITION BY n.CODINTERNOCOMPUTACIONAL
      ORDER BY
        n.FECSOLICITUDEVALUACION ASC,
        n.FLG_OP_PREFIX ASC,
        n.CODEVAL_NUM ASC,
        n.CODEVALUACIONSOLICITUD ASC,
        n.CODSECUENCIALDECISIONRBM ASC,
        n.CODIDEVALUACION ASC
    ) AS PREV_FLG_OP,

    LAG(n.CODEVAL_NUM) OVER (
      PARTITION BY n.CODINTERNOCOMPUTACIONAL
      ORDER BY
        n.FECSOLICITUDEVALUACION ASC,
        n.FLG_OP_PREFIX ASC,
        n.CODEVAL_NUM ASC,
        n.CODEVALUACIONSOLICITUD ASC,
        n.CODSECUENCIALDECISIONRBM ASC,
        n.CODIDEVALUACION ASC
    ) AS PREV_CODEVAL_NUM,

    LAG(n.CODEVALUACIONSOLICITUD) OVER (
      PARTITION BY n.CODINTERNOCOMPUTACIONAL
      ORDER BY
        n.FECSOLICITUDEVALUACION ASC,
        n.FLG_OP_PREFIX ASC,
        n.CODEVAL_NUM ASC,
        n.CODEVALUACIONSOLICITUD ASC,
        n.CODSECUENCIALDECISIONRBM ASC,
        n.CODIDEVALUACION ASC
    ) AS PREV_CODEVAL_TXT
  FROM SOL_NORM n
),

SOL_REING AS (
  SELECT
    o.*,
    CASE
      WHEN o.PREV_FECSOL IS NULL THEN 0
      WHEN (
        o.FECSOLICITUDEVALUACION > o.PREV_FECSOL
        OR (
          o.FECSOLICITUDEVALUACION = o.PREV_FECSOL
          AND (
            o.FLG_OP_PREFIX > o.PREV_FLG_OP
            OR (o.FLG_OP_PREFIX = o.PREV_FLG_OP AND o.CODEVAL_NUM > o.PREV_CODEVAL_NUM)
            OR (o.FLG_OP_PREFIX = o.PREV_FLG_OP AND o.CODEVAL_NUM = o.PREV_CODEVAL_NUM AND o.CODEVALUACIONSOLICITUD > o.PREV_CODEVAL_TXT)
          )
        )
      )
      AND o.FECSOLICITUDEVALUACION <= add_months(o.PREV_FECSOL, 1)
      THEN 1 ELSE 0
    END AS FLG_REINGRESO_1M,

    SUM(
      CASE
        WHEN o.PREV_FECSOL IS NULL THEN 1
        WHEN o.FECSOLICITUDEVALUACION > add_months(o.PREV_FECSOL, 1) THEN 1
        ELSE 0
      END
    ) OVER (
      PARTITION BY o.CODINTERNOCOMPUTACIONAL
      ORDER BY
        o.FECSOLICITUDEVALUACION ASC,
        o.FLG_OP_PREFIX ASC,
        o.CODEVAL_NUM ASC,
        o.CODEVALUACIONSOLICITUD ASC,
        o.CODSECUENCIALDECISIONRBM ASC,
        o.CODIDEVALUACION ASC
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS ID_EPISODIO_1M
  FROM SOL_ORD o
),

VENTA AS (
  SELECT
    CAST(date_format(FECAPERTURA, 'yyyyMM') AS INT) AS CODMESAPERTURA,
    CODSOLICITUD,
    (CASE
      WHEN SUBSTR(TRIM(CODSOLICITUD), 1, 2) IN ('CX', 'DX') THEN SUBSTR(TRIM(CODSOLICITUD), 3, 8)
      WHEN CODSOLICITUD LIKE '2________'                 THEN SUBSTR(TRIM(CODSOLICITUD), 3, 7)
      WHEN CODSOLICITUD LIKE '      2________'           THEN SUBSTR(TRIM(CODSOLICITUD), 3, 7)
      WHEN CODSOLICITUD LIKE 'O%'                        THEN SUBSTR(TRIM(CODSOLICITUD), 3, 7)
      ELSE TRIM(CODSOLICITUD)
    END) AS CODSOLICITUDCORTO,
    (CASE
      WHEN CODPRODUCTO = 'CPEFIA' THEN 'CUOTEALO'
      WHEN SUBSTR(TRIM(CODSOLICITUD), 1, 2) = 'PE' THEN 'CUOTEALO'
      WHEN CODPRODUCTO = 'CPEYAP' THEN 'YAPE'
      WHEN SUBSTR(TRIM(CODSOLICITUD), 1, 2) = 'YP' THEN 'YAPE'
      WHEN SUBSTR(TRIM(CODSOLICITUD), 1, 2) = 'JB' THEN 'BANCA MÓVIL'
      WHEN SUBSTR(TRIM(CODSOLICITUD), 1, 2) IN ('CX', 'DX') THEN 'LOANS'
      WHEN CODSOLICITUD LIKE '2________' THEN 'SALEFORCE'
      WHEN CODSOLICITUD LIKE '      2________' THEN 'SALEFORCE'
      WHEN CODSOLICITUD LIKE 'O%' THEN 'SALEFORCE'
      ELSE 'OTROS'
    END) AS CANAL_MDPREST,
    FECAPERTURA,
    FECDESEMBOLSO,
    MTOORIGINALCREDITO,
    MTODESEMBOLSADO,
    MTODESEMBOLSADOCONTRAVALORSBSSOL,
    CODCLAVEPARTYCLI
  FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.M_CUENTACREDITOPERSONAL
  WHERE CODPRODUCTO IN ('CPEEFM','CPECMC','CPEDPP','CPECEM','CPEECV','CPEGEN','CPEADH','CPEFIA')
    AND FLGREGELIMINADOFUENTE = 'N'
),

MATCH_CAND AS (
  SELECT
    s.*,
    v.CODMESAPERTURA,
    v.CODSOLICITUD,
    v.CODSOLICITUDCORTO,
    v.CANAL_MDPREST,
    v.FECAPERTURA,
    v.FECDESEMBOLSO,
    v.MTOORIGINALCREDITO,
    v.MTODESEMBOLSADO,
    v.MTODESEMBOLSADOCONTRAVALORSBSSOL,
    ABS(datediff(v.FECAPERTURA, s.FECSOLICITUDEVALUACION)) AS ABS_DIF_APERTURA,
    datediff(v.FECAPERTURA, s.FECSOLICITUDEVALUACION) AS DIF_APERTURA
  FROM SOL_REING s
  LEFT JOIN VENTA v
    ON s.CODCLAVEPARTYCLI = v.CODCLAVEPARTYCLI
   AND s.DESCANALVENTARBMPER = v.CANAL_MDPREST
   AND TRIM(s.NUMSOLICITUDEVALUACIONCORTO) = TRIM(v.CODSOLICITUDCORTO)
   AND datediff(v.FECAPERTURA, s.FECSOLICITUDEVALUACION) BETWEEN 0 AND 40
),

MATCH_ONE AS (
  SELECT *
  FROM (
    SELECT
      m.*,
      ROW_NUMBER() OVER (
        PARTITION BY m.CODINTERNOCOMPUTACIONAL, m.CODIDEVALUACION, m.CODEVALUACIONSOLICITUD
        ORDER BY
          m.ABS_DIF_APERTURA ASC,
          m.FECAPERTURA ASC,
          m.CODSOLICITUD ASC
      ) AS RN_MATCH
    FROM MATCH_CAND m
  ) x
  WHERE RN_MATCH = 1
),

BASE_FLAGS AS (
  SELECT
    m.CODEVALUACIONSOLICITUD,
    m.CODINTERNOCOMPUTACIONAL,
    m.CODMESEVALUACION AS CODMESSOLICITUDEVALUACION,
    m.FECSOLICITUDEVALUACION,
    m.DESCANALVENTARBMPER AS DESCANALVENTARBM,
    m.DESTIPDECISIONRESULTADORBM,
    m.DESCAMPANIASOLICITUD,
    m.DESTIPEVALUACIONSOLICITUDCREDITO,
    m.CANAL_MDPREST,
    CASE WHEN m.DESTIPDECISIONRESULTADORBM = 'Approve' THEN 1 ELSE 0 END AS FLG_APROBADO,
    CASE WHEN m.DESTIPDECISIONRESULTADORBM IN ('Decline', 'Investigate') THEN 1 ELSE 0 END AS FLG_DENEGADO,
    m.FLG_REINGRESO_1M,
    CASE WHEN m.DESTIPDECISIONRESULTADORBM = 'Approve' AND m.FECAPERTURA IS NOT NULL THEN 1 ELSE 0 END AS FLG_DESEMBOLSADO,
    CASE WHEN m.DESTIPDECISIONRESULTADORBM = 'Approve' AND m.FECAPERTURA IS NULL     THEN 1 ELSE 0 END AS FLG_NODESEMBOLSADO,
    CASE WHEN m.DESTIPDECISIONRESULTADORBM = 'Approve' AND m.FLG_REINGRESO_1M = 1 AND m.FECAPERTURA IS NOT NULL THEN 1 ELSE 0 END AS FLG_REINGRESO_1M_DESEMBOLSO,
    CASE WHEN m.DESTIPDECISIONRESULTADORBM = 'Approve' AND m.FLG_REINGRESO_1M = 1 AND m.FECAPERTURA IS NULL     THEN 1 ELSE 0 END AS FLG_REINGRESO_1M_NO_DESEMBOLSO,
    CASE WHEN m.DESTIPDECISIONRESULTADORBM = 'Approve' AND m.FLG_REINGRESO_1M = 0 AND m.FECAPERTURA IS NULL     THEN 1 ELSE 0 END AS FLG_NOREINGRESO_NODESEMBOLSO,
    CASE WHEN m.DESTIPDECISIONRESULTADORBM = 'Approve' THEN COALESCE(m.MTODESEMBOLSADO, 0) ELSE 0 END    AS MTODESEMBOLSADO,
    CASE WHEN m.DESTIPDECISIONRESULTADORBM = 'Approve' THEN COALESCE(m.MTOORIGINALCREDITO, 0) ELSE 0 END AS MTOORIGINALCREDITO,
    CASE
      WHEN m.DESTIPDECISIONRESULTADORBM = 'Approve' AND m.FLG_REINGRESO_1M = 1 AND m.FECAPERTURA IS NOT NULL THEN COALESCE(m.MTODESEMBOLSADO, 0)
      ELSE 0
    END AS MTODESEMBOLSADO_REINGRESO_1M
  FROM MATCH_ONE m
),
TP_BASE AS (
SELECT
  CODEVALUACIONSOLICITUD,
  CODINTERNOCOMPUTACIONAL,
  CODMESSOLICITUDEVALUACION,
  FECSOLICITUDEVALUACION,
  DESCANALVENTARBM,
  DESTIPDECISIONRESULTADORBM,
  DESCAMPANIASOLICITUD,
  DESTIPEVALUACIONSOLICITUDCREDITO,
  CANAL_MDPREST,
  FLG_APROBADO,
  FLG_DENEGADO,
  FLG_REINGRESO_1M,
  FLG_DESEMBOLSADO,
  FLG_NODESEMBOLSADO,
  FLG_REINGRESO_1M_DESEMBOLSO,
  FLG_REINGRESO_1M_NO_DESEMBOLSO,
  FLG_NOREINGRESO_NODESEMBOLSO,
  MTODESEMBOLSADO,
  MTOORIGINALCREDITO,
  MTODESEMBOLSADO_REINGRESO_1M
FROM BASE_FLAGS
),
FUNNEL AS (
  SELECT
    CODMESSOLICITUDEVALUACION,
    DESCANALVENTARBM,
    CANAL_MDPREST,
    DESCAMPANIASOLICITUD,
    DESTIPEVALUACIONSOLICITUDCREDITO,
    COUNT(*)                         AS N_SOLICITUDES,
    SUM(FLG_APROBADO)               AS N_APROBADAS,
    SUM(FLG_DENEGADO)               AS N_DENEGADAS,
    SUM(FLG_REINGRESO_1M)           AS N_REINGRESOS,
    SUM(FLG_DESEMBOLSADO)           AS N_DESEMBOLSADAS,
    SUM(FLG_NODESEMBOLSADO)         AS N_NO_DESEMBOLSADAS,
    SUM(FLG_REINGRESO_1M_DESEMBOLSO)    AS N_REINGRESO_DESEMBOLSO,
    SUM(FLG_REINGRESO_1M_NO_DESEMBOLSO) AS N_REINGRESO_NO_DESEMBOLSO,
    SUM(FLG_NOREINGRESO_NODESEMBOLSO)   AS N_NOREINGRESO_NO_DESEMBOLSO,
    SUM(MTODESEMBOLSADO)              AS MTO_TOTAL_DESEMBOLSADO,
    SUM(MTOORIGINALCREDITO)           AS MTO_TOTAL_ORIGINAL,
    SUM(MTODESEMBOLSADO_REINGRESO_1M) AS MTO_DESEMBOLSADO_REINGRESO_1M
  FROM BASE_FLAGS
  WHERE CODMESSOLICITUDEVALUACION BETWEEN 202501 AND 202512 AND DESCANALVENTARBM NOT IN ('SALEFORCE')
  
  GROUP BY
    CODMESSOLICITUDEVALUACION,
    DESCANALVENTARBM,
    CANAL_MDPREST,
    DESCAMPANIASOLICITUD,
    DESTIPEVALUACIONSOLICITUDCREDITO
)
SELECT *
FROM FUNNEL
ORDER BY CODMESSOLICITUDEVALUACION, DESCANALVENTARBM;
