SOLICITUDESUNICAS AS (
  SELECT *
  FROM MD_EVALUACIONSOLICITUDCREDITO
  WHERE EVALUACIONREACTIVO <> '0.No valido'
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CODINTERNOCOMPUTACIONAL, NUMSOLICITUDEVALUACION
    ORDER BY RESULTADORBMJERARQUIA ASC, FECEVALUACION DESC
  ) = 1
)
SELECT *
FROM SOLICITUDESUNICAS;
