WITH
PARAMS AS (
  SELECT
    ${codmes} AS CODMES,
    CAST(date_format(add_months(to_date(CAST(${codmes} AS STRING),'yyyyMM'),1),'yyyyMM') AS INT) AS CODMES_1
),
MD_EVALUACIONSOLICITUDCREDITO AS (
	SELECT
		A.CODEVALUACIONSOLICITUD,
		A.CODIDEVALUACION,
		CAST(date_format(A.FECEVALUACION, 'yyyyMM') AS INT) AS CODMESEVALUACION,
		A.FECEVALUACION,
		A.CODINTERNOCOMPUTACIONAL,
		A.NUMSOLICITUDEVALUACION,
		A.CODSECUENCIALDECISIONRBM,
		A.DESDECISIONEVALUACION,
		A.DESREGLAPAUTA,
		A.DESTIPDECISIONRESULTADORBM,
		A.DESEVALUACION,
		A.MTOCEMEVALUACION,
		A.DESCAMPANIASOLICITUD,
		A.DESTIPEVALUACIONSOLICITUDCREDITO,
		A.DESCANALVENTARBMPER,
		(CASE
			WHEN A.DESCANALVENTARBMPER = 'SALEFORCE' THEN SUBSTR(TRIM(A.NUMSOLICITUDEVALUACION), 5, 7)
			WHEN A.DESCANALVENTARBMPER = 'LOANS' THEN SUBSTR(TRIM(A.NUMSOLICITUDEVALUACION), 3, 8)
			ELSE TRIM(A.NUMSOLICITUDEVALUACION)
		END) AS NUMSOLICITUDCORTO,
		(CASE
			WHEN A.DESTIPDECISIONRESULTADORBM = 'Approve' then 1
			WHEN A.DESTIPDECISIONRESULTADORBM = 'Decline' then 3
			ELSE 2
		END) AS RESULTADORBMJERARQUIA,
		(CASE
			WHEN A.DESCANALVENTARBMPER = 'BANCA MÓVIL' AND A.DESEVALUACION = 'df_Regular' THEN '0.No valido'
			WHEN A.DESCAMPANIASOLICITUD = 'Reactivo' THEN '1.Reactivo'
			ELSE '2.No Reactivo'
		END) AS EVALUACIONREACTIVO,
		(CASE
			WHEN A.DESTIPEVALUACIONSOLICITUDCREDITO IN ('Regular LD', 'Cuotealo') AND A.DESCAMPANIASOLICITUD IN ('100% Aprobado', 'Pre-Aprobado') THEN 'LD APR'
			WHEN A.DESTIPEVALUACIONSOLICITUDCREDITO IN ('Regular LD', 'Cuotealo') AND A.DESCAMPANIASOLICITUD = 'CEF Shield' THEN 'LD SHD'
			WHEN A.DESTIPEVALUACIONSOLICITUDCREDITO = 'Regular LD' AND A.DESCAMPANIASOLICITUD = 'Convenio' THEN 'LD CONV'
			WHEN A.DESTIPEVALUACIONSOLICITUDCREDITO = 'Regular LD' AND A.DESCAMPANIASOLICITUD = 'Invitado' THEN 'LD INV'
			
			WHEN A.DESTIPEVALUACIONSOLICITUDCREDITO = 'Compra de Deuda' AND A.DESCAMPANIASOLICITUD IN ('100% Aprobado', 'Pre-Aprobado') THEN 'CDD APR'
			WHEN A.DESTIPEVALUACIONSOLICITUDCREDITO = 'Compra de Deuda' AND A.DESCAMPANIASOLICITUD = 'Convenio' THEN 'CDD CONV'
			
			WHEN A.DESTIPEVALUACIONSOLICITUDCREDITO = 'LD + Consolidación' AND A.DESCAMPANIASOLICITUD IN ('100% Aprobado', 'Pre-Aprobado') THEN 'REE APR'
			WHEN A.DESTIPEVALUACIONSOLICITUDCREDITO = 'LD + Consolidación' AND A.DESCAMPANIASOLICITUD = 'Convenio'  THEN 'REE CONV'
			
			WHEN A.DESTIPEVALUACIONSOLICITUDCREDITO = 'LD + Compra de Deuda + Consolidación' AND A.DESCAMPANIASOLICITUD IN ('100% Aprobado', 'Pre-Aprobado') THEN 'CONS APR'
			WHEN A.DESTIPEVALUACIONSOLICITUDCREDITO = 'LD + Compra de Deuda + Consolidación' AND A.DESCAMPANIASOLICITUD = 'Convenio' THEN 'CONS CONV'
			
			ELSE 'REACTIVO'
		END) AS LEAD_CEF
	FROM CATALOG_LHCL_PROD_BCP.BCP_DDV_RBMRBMPER_MODELOGESTION_VU.MD_EVALUACIONSOLICITUDCREDITO A
	CROSS JOIN PARAMS P
	WHERE A.TIPPRODUCTOSOLICITUDRBM = 'CC' AND A.DESCANALVENTARBMPER NOT IN ('YAPE', 'OTROS') AND A.CODMESEVALUACION = P.CODMES
),
SOLICITUDESUNICAS AS (
	SELECT *
	FROM MD_EVALUACIONSOLICITUDCREDITO
	WHERE EVALUACIONREACTIVO <> '0.No valido'
	QUALIFY ROW_NUMBER() OVER (
		PARTITION BY CODINTERNOCOMPUTACIONAL, NUMSOLICITUDEVALUACION
		ORDER BY RESULTADORBMJERARQUIA ASC, FECEVALUACION DESC
	) = 1
),
H_TIPOCAMBIO AS (
	SELECT
		CAST(date_format(A.FECTIPCAMBIO, 'yyyyMM') AS INT) AS CODMES,
		A.FECTIPCAMBIO,
		A.CODMONEDAORIGEN,
		A.CODMONEDADESTINO,
		A.MTOCAMBIOMONEDAORIGENMONEDADESTINO
	FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.H_TIPOCAMBIO A
	CROSS JOIN PARAMS P
	WHERE A.CODMONEDADESTINO = '0001' AND A.CODAPP = 'GLM' AND CAST(date_format(A.FECTIPCAMBIO, 'yyyyMM') AS INT) BETWEEN P.CODMES AND P.CODMES_1
),
TP_TIPOCAMBIO_MAXDAY AS (
	SELECT
		CODMES,
		MAX(FECTIPCAMBIO) AS FECTIPCAMBIO
	FROM H_TIPOCAMBIO
	GROUP BY CODMES
),
M_TIPOCAMBIO AS (
	SELECT
		A.CODMES,
		A.FECTIPCAMBIO,
		A.CODMONEDAORIGEN,
		A.CODMONEDADESTINO,
		A.MTOCAMBIOMONEDAORIGENMONEDADESTINO
	FROM H_TIPOCAMBIO A
	JOIN TP_TIPOCAMBIO_MAXDAY B ON (A.CODMES = B.CODMES AND A.FECTIPCAMBIO = B.FECTIPCAMBIO)
	QUALIFY ROW_NUMBER() OVER (
		PARTITION BY A.CODMES, A.CODMONEDAORIGEN
		ORDER BY A.CODMONEDAORIGEN
	) = 1
),
M_CLIENTE AS (
	SELECT
		CODCLAVEPARTYCLI,
		CODCLAVEUNICOCLI,
		CODINTERNOCOMPUTACIONAL
	FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.M_CLIENTE
),
M_CUENTACREDITOPERSONAL AS (
	SELECT
		CAST(date_format(A.FECAPERTURA, 'yyyyMM') AS INT) AS CODMESAPERTURA,
		CAST(A.FECAPERTURA AS DATE) AS FECAPERTURA,
		CAST(A.FECDESEMBOLSO AS DATE) AS FECDESEMBOLSO,
		A.CODCLAVECTA,
		A.CODSOLICITUD,
		A.CODCLAVEPARTYCLI,
		A.CODPRODUCTO,
		A.MTODESEMBOLSADO,
		A.CODMONEDA
	FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.M_CUENTACREDITOPERSONAL A
	CROSS JOIN PARAMS P
	WHERE
		CAST(date_format(A.FECAPERTURA, 'yyyyMM') AS INT) BETWEEN P.CODMES AND P.CODMES_1 
		AND FLGREGELIMINADOFUENTE = 'N'
		AND A.CODPRODUCTO IN ('CPEEFM','CPECMC','CPEDPP','CPECEM','CPEECV','CPEGEN','CPEADH','CPEFIA')
),
TP_CUENTACREDITOPERSONAL AS (
	SELECT
		A.CODMESAPERTURA,
		A.FECAPERTURA,
		A.FECDESEMBOLSO,
		A.CODCLAVECTA,
		A.CODSOLICITUD,
		A.CODCLAVEPARTYCLI,
		C.CODCLAVEUNICOCLI,
		C.CODINTERNOCOMPUTACIONAL,
		A.CODPRODUCTO,
		A.MTODESEMBOLSADO,
		A.CODMONEDA,
		(CASE
			WHEN A.CODMONEDA <> '0001' THEN A.MTODESEMBOLSADO * B.MTOCAMBIOMONEDAORIGENMONEDADESTINO
			ELSE A.MTODESEMBOLSADO
		END) AS MTODESEMBOLSADOSOLES,
		(CASE
			WHEN SUBSTR(TRIM(A.CODSOLICITUD), 1, 2) IN ('CX', 'DX') THEN SUBSTR(TRIM(A.CODSOLICITUD), 3, 8) --LOANS
			WHEN A.CODSOLICITUD LIKE '2________' THEN SUBSTR(TRIM(A.CODSOLICITUD), 3, 7) -- SF
			WHEN A.CODSOLICITUD LIKE '      2________' THEN SUBSTR(TRIM(A.CODSOLICITUD), 3, 7) -- SF
			WHEN A.CODSOLICITUD LIKE 'O%' THEN SUBSTR(TRIM(A.CODSOLICITUD), 3, 7) -- SF
			ELSE TRIM(A.CODSOLICITUD) -- BMO / CUOTEALO
		END) AS CODSOLICITUDCORTO,
		(CASE
			WHEN A.CODPRODUCTO = 'CPEFIA' THEN 'CUOTEALO'
			WHEN SUBSTR(TRIM(A.CODSOLICITUD), 1, 2) = 'PE' THEN 'CUOTEALO'
			WHEN A.CODPRODUCTO = 'CPEYAP' THEN 'YAPE'
			WHEN SUBSTR(TRIM(A.CODSOLICITUD), 1, 2) = 'YP' THEN 'YAPE'
			WHEN SUBSTR(TRIM(A.CODSOLICITUD), 1, 2) = 'JB' THEN 'BANCA MÓVIL'
			WHEN SUBSTR(TRIM(A.CODSOLICITUD), 1, 2) IN ('CX', 'DX') THEN 'LOANS'
			WHEN A.CODSOLICITUD LIKE '2________' THEN 'SALEFORCE'
			WHEN A.CODSOLICITUD LIKE '      2________' THEN 'SALEFORCE'
			WHEN A.CODSOLICITUD LIKE 'O%' THEN 'SALEFORCE'
			ELSE 'OTROS'
		END) AS CANAL_MDPREST
	FROM M_CUENTACREDITOPERSONAL A
	LEFT JOIN M_TIPOCAMBIO B ON (CAST(date_format(A.FECAPERTURA, 'yyyyMM') AS INT) = B.CODMES AND A.CODMONEDA = B.CODMONEDAORIGEN)
	LEFT JOIN M_CLIENTE C ON (A.CODCLAVEPARTYCLI = C.CODCLAVEPARTYCLI)
),
M_SOLICITUDCREDITOCONSUMO AS (
	SELECT
		CAST(date_format(A.FECSOLICITUD, 'yyyyMM') AS INT) AS CODMESSOLICITUD,
		A.FECSOLICITUD,
		A.HORSOLICITUD,
		A.CODSOLICITUD,
		A.CODINTERNOCOMPUTACIONAL,
		A.TIPESTADOSOLICITUD,
		A.DESTIPESTADOSOLICITUD,
		A.FLGDESEMBOLSOSOLICITUD,
		A.FECULTESTADOSOLICITUD,
		A.CODPRODUCTO,
		A.CODAPPSOLICITUD,
		A.FLGVENTACEF,
		A.FLGCOMPRADEUDA,
		A.FLGCOMPRADEUDAADJUNTA,
		A.MTOSOLICITADOCDD,
		A.DESTIPRESULTADO,
		A.DESPRODUCTO,
		A.CODMONEDA,
		A.NUMDIAPAGOCUOTA,
		A.MTOSOLICITADO,
		A.CTDPLAZOSOLICITADO,
		A.PCTTASAEFECTIVAANUALSOLICITUD,
		A.MTOCUOTAMENSUALSOLICITADO,
		A.MTOAPROBADO,
		A.CTDPLAZOAPROBADO,
		A.PCTTASAEFECTIVAANUALAPROBADA,
		A.MTOCUOTAMENSUALAPROBADO,
		A.CODMATRICULACOLABORADORANALISTA,
		A.CODMATRICULACOLABORADOREXCEPTUADOR,
		A.CODMATRICULACOLABORADORAUTONOMOCENTRALIZADO,
		A.CODMATRICULACOLABORADORVENDEDOR,
		A.CODMATRICULACOLABORADORAPROBADOR,
		A.CODSECTORISTA,
		A.TIPEVALUACIONSOLICITUD,
		A.DESTIPEVALUACIONSOLICITUD,
		A.TIPFORMAPAGO,
		A.DESTIPFORMAPAGO,
		A.TIPESTADOJUSTIFICACIONSOLICITUD,
		A.DESTIPESTADOJUSTIFICACIONSOLICITUD,
		A.FECINICIOCALIF,
		A.DESTIPVENTACDA,
		A.FLGEXCEP,
		A.NBRTIPEXCEP,
		A.NBREXCEP,
		A.FECDESEMBOLSO,
		A.FECABONOEFECTIVO,
		A.FLGNUEVACTAABONO,
		A.PCTTASACOSTOEFECTIVO,
		A.PCTTASASEGURODESGRAVAMEN,
		A.NUMCOTIZACIONPRICING,
		A.DESTIPETAPA
	FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.M_SOLICITUDCREDITOCONSUMO A
	CROSS JOIN PARAMS P
	WHERE CAST(date_format(A.FECSOLICITUD, 'yyyyMM') AS INT) = P.CODMES
),
VENTAS_SOLICITUDES AS (
	SELECT
		A.*,
		B.CODMESAPERTURA,
		B.FECAPERTURA,
		B.FECDESEMBOLSO,
		B.CODCLAVECTA,
		B.CODSOLICITUD,
		B.CODCLAVEPARTYCLI,
		B.CODCLAVEUNICOCLI,
		B.CODINTERNOCOMPUTACIONAL,
		B.CODPRODUCTO,
		B.MTODESEMBOLSADO,
		B.CODMONEDA,
		B.MTODESEMBOLSADOSOLES,
		B.CODSOLICITUDCORTO,
		B.CANAL_MDPREST,
		C.*
	FROM SOLICITUDESUNICAS A
	LEFT JOIN TP_CUENTACREDITOPERSONAL B ON (A.NUMSOLICITUDCORTO = B.CODSOLICITUDCORTO AND A.DESCANALVENTARBMPER = B.CANAL_MDPREST AND TRIM(A.CODINTERNOCOMPUTACIONAL) = TRIM(B.CODINTERNOCOMPUTACIONAL))
	LEFT JOIN M_SOLICITUDCREDITOCONSUMO C ON (A.CODMESEVALUACION = C.CODMESSOLICITUD AND A.NUMSOLICITUDEVALUACION = C.CODSOLICITUD)
),
HM_LEADS_BDI AS (
	SELECT
		CODLOTEOFERTA,
		CODINTERNOCOMPUTACIONAL,
		TIPVENTA,
		TIPOFERTA,
		DESCAMPANA,
		CODCONDICIONCLIENTE,
		ROUND(MTOFINALOFERTADOSOL, 1) AS MTOFINALOFERTADOSOL,
		ROUND(NUMPLAZO, 0) AS NUMPLAZO,
		PCTTASAEFECTIVAANUAL,
		FECINICIOVIGENCIA,
		(CASE
			WHEN TIPVENTA = 6 AND TIPOFERTA = 3 AND CODCONDICIONCLIENTE = 'INV' THEN 'CEF LD INVITADO'
			WHEN TIPVENTA = 6 AND TIPOFERTA = 3 AND CODCONDICIONCLIENTE = 'PRE' THEN 'CEF LD PREAPROBADO'
			WHEN TIPVENTA = 6 AND TIPOFERTA = 3 AND CODCONDICIONCLIENTE = 'APR' THEN 'CEF LD 100% APROBADO'
			WHEN TIPVENTA = 6 AND TIPOFERTA = 3 AND CODCONDICIONCLIENTE = 'OPT' THEN 'CEF LD OPTIMUS'
			WHEN TIPVENTA = 6 AND TIPOFERTA IN (89, 98) THEN 'CEF SHIELD'
			WHEN TIPVENTA = 6 AND TIPOFERTA = 41 AND CODCONDICIONCLIENTE = 'PRE' THEN 'CEF CDD PREAPROBADO'
			WHEN TIPVENTA = 6 AND TIPOFERTA = 41 AND CODCONDICIONCLIENTE = 'APR' THEN 'CEF CDD 100% APROBADO'
			WHEN TIPVENTA = 6 AND TIPOFERTA = 187 THEN 'CEF CDD INSUPERABLE'
			WHEN TIPVENTA = 6 AND TIPOFERTA = 38 AND CODCONDICIONCLIENTE = 'PRE' THEN 'CEF RE PREAPROBADO'
			WHEN TIPVENTA = 6 AND TIPOFERTA = 38 AND CODCONDICIONCLIENTE = 'APR' THEN 'CEF RE 100% APROBADO'
			WHEN TIPVENTA = 110 AND TIPOFERTA = 3 THEN 'CEF CONVENIO LD'
			WHEN TIPVENTA = 110 AND TIPOFERTA = 41 THEN 'CEF CONVENIO CDD'
			WHEN TIPVENTA = 110 AND TIPOFERTA = 38 THEN 'CEF CONVENIO RE'
		END) AS PRODUCTO,
		ROW_NUMBER() OVER (
			PARTITION BY CODLOTEOFERTA, CODINTERNOCOMPUTACIONAL, TIPVENTA, TIPOFERTA
			ORDER BY FECINICIOVIGENCIA
		) AS N
	FROM CATALOG_LHCL_PROD_BCP.BCP_EDV_RBMBDN.HM_LEADS_BDI
	WHERE CODPAUTARBM <> 41 AND TIPVENTA IN (6,110) AND DESCAMPANA NOT IN ('CREDITO PERSONAL, VENTA AMPLIACION PLAZO', 'VENTA SKIP')
),
BASE_LEADS AS (
	SELECT
		A.CODLOTEOFERTA,
		A.CODINTERNOCOMPUTACIONAL,
		A.TIPVENTA,
		A.TIPOFERTA,
		A.DESCAMPANA,
		A.CODCONDICIONCLIENTE,
		A.MTOFINALOFERTADOSOL,
		A.NUMPLAZO,
		A.PCTTASAEFECTIVAANUAL,
		(CASE
			WHEN A.TIPVENTA = 6 AND A.TIPOFERTA = 3 AND A.CODCONDICIONCLIENTE IN ('APR', 'PRE') THEN 1
			WHEN A.TIPVENTA = 6 AND A.TIPOFERTA = 3 AND A.CODCONDICIONCLIENTE = 'OPT' THEN 2
			WHEN A.TIPVENTA = 6 AND A.TIPOFERTA = 41 AND A.CODCONDICIONCLIENTE IN ('APR', 'PRE') THEN 3
			WHEN A.TIPVENTA = 6 AND A.TIPOFERTA = 38 AND A.CODCONDICIONCLIENTE IN ('APR', 'PRE') THEN 4
			WHEN A.TIPVENTA = 6 AND A.TIPOFERTA IN (89, 98) THEN 5
			WHEN A.TIPVENTA = 6 AND A.TIPOFERTA = 3 AND A.CODCONDICIONCLIENTE = 'INV' THEN 6
			WHEN A.TIPVENTA = 6 AND A.TIPOFERTA = 187 THEN 7
			WHEN A.TIPVENTA = 110 AND A.TIPOFERTA = 3 THEN 8
			WHEN A.TIPVENTA = 110 AND A.TIPOFERTA = 41 THEN 9
			WHEN A.TIPVENTA = 110 AND A.TIPOFERTA = 38 THEN 10
			ELSE 11
		END) AS PRIORIDADLEAD,
		(CASE
			WHEN A.TIPVENTA = 6 AND A.TIPOFERTA = 3 AND A.CODCONDICIONCLIENTE IN ('APR', 'PRE') THEN 'LD APR'
			WHEN A.TIPVENTA = 6 AND A.TIPOFERTA = 3 AND A.CODCONDICIONCLIENTE = 'OPT' THEN 'LD OPT'
			WHEN A.TIPVENTA = 6 AND A.TIPOFERTA = 41 AND A.CODCONDICIONCLIENTE IN ('APR', 'PRE') THEN 'CDD APR'
			WHEN A.TIPVENTA = 6 AND A.TIPOFERTA = 38 AND A.CODCONDICIONCLIENTE IN ('APR', 'PRE') THEN 'REE APR'
			WHEN A.TIPVENTA = 6 AND A.TIPOFERTA IN (89, 98) THEN 'LD SHD'
			WHEN A.TIPVENTA = 6 AND A.TIPOFERTA = 3 AND A.CODCONDICIONCLIENTE = 'INV' THEN 'LD INV'
			WHEN A.TIPVENTA = 6 AND A.TIPOFERTA = 187 THEN 'CDD INS'
			WHEN A.TIPVENTA = 110 AND A.TIPOFERTA = 3 THEN 'LD CONV'
			WHEN A.TIPVENTA = 110 AND A.TIPOFERTA = 41 THEN 'CDD CONV'
			WHEN A.TIPVENTA = 110 AND A.TIPOFERTA = 38 THEN 'REE CONV'
--			WHEN A.TIPVENTA = 127 AND A.TIPOFERTA = 3 THEN 'LD MULTI' - FALTA TRAER TIPVENTA 127 DE BASE DE LEADS
			ELSE 'OTRO'
		END) AS LEAD_CEF
	FROM HM_LEADS_BDI A
	CROSS JOIN PARAMS P
	WHERE A.N = 1 AND PRODUCTO IS NOT NULL AND A.CODLOTEOFERTA = P.CODMES
),
LEADS_UNICOS AS (
	SELECT
		A.*
	FROM BASE_LEADS A
	QUALIFY ROW_NUMBER() OVER (
		PARTITION BY A.CODINTERNOCOMPUTACIONAL
		ORDER BY A.PRIORIDADLEAD ASC, A.CODLOTEOFERTA DESC, A.TIPVENTA ASC, A.TIPOFERTA ASC
	) = 1
),
SOLICITUDES_LEAD AS (
	SELECT
		A.*,
		(CASE
			WHEN A.LEAD_CEF IN ('REACTIVO','CONS APR','CONS CONV') THEN C.CODLOTEOFERTA
			ELSE COALESCE(B.CODLOTEOFERTA, C.CODLOTEOFERTA)
		END) AS CODLOTEOFERTA,
		(CASE
			WHEN A.LEAD_CEF IN ('REACTIVO','CONS APR','CONS CONV') THEN C.TIPVENTA
			ELSE COALESCE(B.TIPVENTA, C.TIPVENTA)
		END) AS TIPVENTA,
		(CASE
			WHEN A.LEAD_CEF IN ('REACTIVO','CONS APR','CONS CONV') THEN C.TIPOFERTA
			ELSE COALESCE(B.TIPOFERTA, C.TIPOFERTA)
		END) AS TIPOFERTA,
		(CASE
			WHEN A.LEAD_CEF IN ('REACTIVO','CONS APR','CONS CONV') THEN C.DESCAMPANA
			ELSE COALESCE(B.DESCAMPANA, C.DESCAMPANA)
		END) AS DESCAMPANA,
		(CASE
			WHEN A.LEAD_CEF IN ('REACTIVO','CONS APR','CONS CONV') THEN C.CODCONDICIONCLIENTE
			ELSE COALESCE(B.CODCONDICIONCLIENTE, C.CODCONDICIONCLIENTE)
		END) AS CODCONDICIONCLIENTE,
		(CASE
			WHEN A.LEAD_CEF IN ('REACTIVO','CONS APR','CONS CONV') THEN C.MTOFINALOFERTADOSOL
			ELSE COALESCE(B.MTOFINALOFERTADOSOL, C.MTOFINALOFERTADOSOL)
		END) AS MTOFINALOFERTADOSOL,
		(CASE
			WHEN A.LEAD_CEF IN ('REACTIVO','CONS APR','CONS CONV') THEN C.NUMPLAZO
			ELSE COALESCE(B.NUMPLAZO, C.NUMPLAZO)
		END) AS NUMPLAZO,
		(CASE
			WHEN A.LEAD_CEF IN ('REACTIVO','CONS APR','CONS CONV') THEN C.PCTTASAEFECTIVAANUAL
			ELSE COALESCE(B.PCTTASAEFECTIVAANUAL, C.PCTTASAEFECTIVAANUAL)
		END) AS PCTTASAEFECTIVAANUAL
	FROM VENTAS_SOLICITUDES A
	LEFT JOIN LEADS_UNICOS B ON TRIM(A.CODINTERNOCOMPUTACIONAL) = TRIM(B.CODINTERNOCOMPUTACIONAL) AND A.LEAD_CEF = B.LEAD_CEF
	LEFT JOIN LEADS_UNICOS C ON TRIM(A.CODINTERNOCOMPUTACIONAL) = TRIM(C.CODINTERNOCOMPUTACIONAL)
)
