WITH
SOLICITUDES_CENTRALIZADO AS (
  SELECT
    MES AS CODMES,
    to_date((SUBSTRING(FECSOLICITUD, 1, 10)), 'dd/MM/yyyy') AS FECSOLICITUD,
    CODSOLICITUD,
    ESTADOFINAL,
    ETAPA,
    CANAL
  FROM CATALOG_LHCL_PROD_BCP.BCP_EDV_RBMBDN.T72496_PLANCHON
  WHERE PRODUCTO = 'CREDITO EFECTIVO'
),
M_SOLICITUDCREDITOCONSUMO AS (
  SELECT
    CODSOLICITUD,
    CODINTERNOCOMPUTACIONAL,
    FECDESEMBOLSO
  FROM CATALOG_LHCL_PROD_BCP.BCP_UDV_INT_VU.M_SOLICITUDCREDITOCONSUMO
),
BASE AS (
  SELECT
    A.CODMES,
    A.CODSOLICITUD,
    CAST(A.FECSOLICITUD AS DATE) AS FECSOLICITUD,
    A.CANAL,
    A.ETAPA,
    A.ESTADOFINAL,
    B.CODINTERNOCOMPUTACIONAL,
    CAST(B.FECDESEMBOLSO AS DATE) AS FECDESEMBOLSO
  FROM SOLICITUDES_CENTRALIZADO A
  LEFT JOIN M_SOLICITUDCREDITOCONSUMO B
    ON A.CODSOLICITUD = B.CODSOLICITUD
  WHERE B.CODINTERNOCOMPUTACIONAL IS NOT NULL
),
REINGRESO AS (
  SELECT
    x.*,
    CASE WHEN COUNT(r.CODSOLICITUD) > 0 THEN 1 ELSE 0 END AS FLAG_REINGRESO_1M_CAL
  FROM BASE x
  LEFT JOIN BASE r
    ON r.CODINTERNOCOMPUTACIONAL = x.CODINTERNOCOMPUTACIONAL
   AND r.ESTADOFINAL = 'DENEGADAS'
   AND (
        r.FECSOLICITUD < x.FECSOLICITUD
        OR (r.FECSOLICITUD = x.FECSOLICITUD AND r.CODSOLICITUD < x.CODSOLICITUD)
       )
   AND r.FECSOLICITUD >= add_months(x.FECSOLICITUD, -1)
  GROUP BY
    x.CODMES, x.CODSOLICITUD, x.FECSOLICITUD, x.CANAL,
    x.ETAPA, x.ESTADOFINAL, x.CODINTERNOCOMPUTACIONAL, x.FECDESEMBOLSO
)
SELECT
  *,
  CASE WHEN ESTADOFINAL = 'ACEPTADAS' AND FLAG_REINGRESO_1M_CAL = 1 THEN 1 ELSE 0 END AS FLAG_APROBADO_REINGRESO_1M_CAL,
  CASE WHEN FECDESEMBOLSO IS NOT NULL THEN 1 ELSE 0 END AS FLAG_DESEMBOLSADO,
  CASE
    WHEN ESTADOFINAL = 'ACEPTADAS'
     AND FLAG_REINGRESO_1M_CAL = 1
     AND FECDESEMBOLSO IS NOT NULL
    THEN 1 ELSE 0
  END AS FLAG_REINGRESO_APROBADO_DESEMBOLSADO_1M_CAL
FROM REINGRESO
ORDER BY FECSOLICITUD DESC;
